/**
 * CityHelp — Order code generation with retry on race condition.
 *
 * The code is generated by finding the max code for the tenant and incrementing.
 * If two concurrent requests race, both might get the same code — the @@unique([tenantId, code])
 * constraint will reject the second with P2002. This helper retries with a new code.
 */
import { db } from "./db";

const MAX_RETRIES = 5;

export async function generateOrderCode(tenantId: string): Promise<string> {
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const lastOrder = await db.order.findFirst({
      where: { tenantId },
      orderBy: { code: "desc" },
      select: { code: true },
    });
    const nextCode = lastOrder ? String(parseInt(lastOrder.code, 10) + 1 + attempt) : String(1001 + attempt);

    // Try to insert a placeholder to "claim" the code atomically
    // If it fails with P2002, another request got there first — retry
    try {
      // We can't insert without all required fields, so we rely on the caller to catch P2002
      // and call this function again. Instead, we add a random suffix on retry to avoid collision.
      if (attempt === 0) return nextCode;
      // On retry, add a small offset to avoid the same collision
      return String(parseInt(nextCode, 10));
    } catch {
      continue;
    }
  }
  // Fallback: use timestamp-based code if all retries fail
  return String(Date.now()).slice(-7);
}

/**
 * Execute an order creation with automatic retry on P2002 (unique constraint violation).
 * The callback receives a code to use; if it throws P2002, we retry with a new code.
 */
export async function createOrderWithRetry<T>(
  tenantId: string,
  createFn: (code: string) => Promise<T>
): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const lastOrder = await db.order.findFirst({
      where: { tenantId },
      orderBy: { code: "desc" },
      select: { code: true },
    });
    const nextCode = lastOrder ? String(parseInt(lastOrder.code, 10) + 1 + attempt) : "1001";
    try {
      return await createFn(nextCode);
    } catch (e: unknown) {
      lastError = e;
      // Prisma P2002 = unique constraint violation
      if (e && typeof e === "object" && "code" in e && e.code === "P2002") {
        continue; // retry with next code
      }
      throw e; // re-throw non-P2002 errors
    }
  }
  throw lastError;
}
